// <auto-generated />
using System;
using APIParks.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace APIParks.Migrations
{
    [DbContext(typeof(APIParksContext))]
    [Migration("20210123000104_AddUser")]
    partial class AddUser
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("APIParks.Models.National", b =>
                {
                    b.Property<int>("NationalId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("NationalParkDescription");

                    b.Property<string>("NationalParkLocation");

                    b.Property<string>("NationalParkName");

                    b.HasKey("NationalId");

                    b.ToTable("Nationals");

                    b.HasData(
                        new
                        {
                            NationalId = 1,
                            NationalParkDescription = "Yellowstone National Park features dramatic canyons, alpine rivers, lush forests, hot springs, and gushing geysers, including its most famous, Old Faithful. Yellowstone Lake is one of the largest high-elevation lakes in North America and is centered over the Yellowstone Caldera, the largest super-volcano on the continent.",
                            NationalParkLocation = "Wyoming",
                            NationalParkName = "Yellowstone National Park"
                        },
                        new
                        {
                            NationalId = 2,
                            NationalParkDescription = "Grand Teton National Park features the major peaks of the 40-mile long Teton Range, as well as most of the northern sections of the valley known as Jackson Hole. The park is named for Grand Teton, the tallest mountain in the Teton Range.",
                            NationalParkLocation = "Wyoming",
                            NationalParkName = "Grand Teton National Park"
                        },
                        new
                        {
                            NationalId = 3,
                            NationalParkDescription = "Haleakala National Park is named after Haleakala, a dormant volcano within its boundaries. The name is Hawaiian for 'house of the sun'. According to a local legend, the demigod Maui imprisoned the sun here in order to lengthen the day.",
                            NationalParkLocation = "Hawaii",
                            NationalParkName = "Haleakala National Park"
                        },
                        new
                        {
                            NationalId = 4,
                            NationalParkDescription = "Mount Rainier National Park features Mount Rainier, also known as Tahoma or Tacoma, a large active stratovolcano in the Cascade Range of the Pacific Northwest. The highest point in the Cascade Range, Mount Rainier is surrounded by valleys, waterfalls, subalpine meadows, and 91,000 acres of old-growth forest. More than 25 glaciers descend the flanks of the volcano. Carbon Glacier is the largest glacier by volume in the contiguous United States, while Emmons Glacier is the largest glacier by area.",
                            NationalParkLocation = "Washington",
                            NationalParkName = "Mount Rainier National Park"
                        },
                        new
                        {
                            NationalId = 5,
                            NationalParkDescription = "Crater Lake Nation Park encompasses the caldera of Crater Lake, a remnant of Mount Mazama, a destroyed volcano, and the surrounding hills and forests. Carter lake is the deepest lake in the United States, second-deepest in North America and the ninth deepest in the world. It has no streams flowing into or out of it. All water that enters the lake is eventually last from evaporation or subsurface seepage. The lake's water commonly has a striking blue hue, and the lake is refilled entirely from direct precipitation in the form of snow and rain.",
                            NationalParkLocation = "Oregon",
                            NationalParkName = "Crater Lake National Park"
                        });
                });

            modelBuilder.Entity("APIParks.Models.State", b =>
                {
                    b.Property<int>("StateId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("StateParkDescription");

                    b.Property<string>("StateParkLocation");

                    b.Property<string>("StateParkName");

                    b.HasKey("StateId");

                    b.ToTable("States");

                    b.HasData(
                        new
                        {
                            StateId = 1,
                            StateParkDescription = "Iao Valley State Park features a dense rainforest canopy. It is dominated by the Iao Needle, a 1,200ft vegetation-covered lava remnant that rises from the valley floor to a higher height than the Eiffel Tower. ",
                            StateParkLocation = "Hawaii",
                            StateParkName = "Iao Valley State Park"
                        },
                        new
                        {
                            StateId = 2,
                            StateParkDescription = "Eldorado Canyon State Park consists of two areas, the Inner Canyon and Crescent Meadows. It is home to one of the world's most accessible and comprehensive rock climbing areas.",
                            StateParkLocation = "Colorado",
                            StateParkName = "Eldorado Canyon State Park"
                        },
                        new
                        {
                            StateId = 3,
                            StateParkDescription = "Niagara Falls State Park is recognized at the oldest state park in the United States. It contains the American Falls, the Bridal Veil Falls, and a portion of the Horseshoe Falls (also known as the Canadian Falls).",
                            StateParkLocation = "New York",
                            StateParkName = "Niagara Falls State Park"
                        },
                        new
                        {
                            StateId = 4,
                            StateParkDescription = "Na Pali Coast State Park is located on the oldest inhabited Hawaiian Island, Kaua'i. It is known for its towering pali, or sea cliffs, narrow valleys, streams and cascading waterfalls. The state park was formed to protect the Kalalau Valley. ",
                            StateParkLocation = "Hawaii",
                            StateParkName = "Na Pali Coast State Park"
                        },
                        new
                        {
                            StateId = 5,
                            StateParkDescription = "Palouse Falls State Park is named for the 200ft Palouse Falls, formerly known as Aput Aput, meaning 'Falling Water', so named by the Palouse Indians on the Palouse River. ",
                            StateParkLocation = "Washington",
                            StateParkName = "Palouse Falls State Park"
                        });
                });

            modelBuilder.Entity("APIParks.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<string>("Username");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
